#ifndef SAFETY_CONFIG_H
#define SAFETY_CONFIG_H

/* Safety task scheduling */
#define SAFETY_TASK_STACK 6144
#define SAFETY_TASK_PRIORITY 4
#define SAFETY_INTERVAL_MS 500
#define SAFETY_HEARTBEAT_TIMEOUT_MS 5000

/* Watchdog and reset resilience */
#define SAFETY_WDT_TIMEOUT_SEC 8
#define SAFETY_RESET_WINDOW_SEC 300
#define SAFETY_RESET_MAX_COUNT 5
#define SAFETY_WDT_RESET_MAX_COUNT 3

/* Topic suffixes */
#define SAFETY_FAULT_TOPIC_SUFFIX "safety/fault"
#define SAFETY_CLEAR_TOPIC_SUFFIX "safety/clear"

/* Dosing supervision */
#define SAFETY_DOSE_WINDOW_MS 300000
#define SAFETY_MAX_DOSE_A_MS 30000
#define SAFETY_MAX_DOSE_B_MS 30000
#define SAFETY_MAX_DOSE_PH_UP_MS 15000
#define SAFETY_MAX_DOSE_PH_DOWN_MS 15000

/* Water level / fill behavior */
#define SAFETY_LEVEL_LOW_DEBOUNCE_MS 300
#define SAFETY_FILL_TIMEOUT_MS 45000

/* Temperature checks (Celsius) */
#define SAFETY_TEMP_LOW 10.0f
#define SAFETY_TEMP_HIGH 36.0f
#define SAFETY_TEMP_CRITICAL 42.0f
#define SAFETY_TEMP_FROZEN_EPSILON 0.02f
#define SAFETY_TEMP_FROZEN_SAMPLES 20

/* pH / TDS checks */
#define SAFETY_ENABLE_PH_TDS_CHECKS 1

#define SAFETY_PH_MIN 4.5f
#define SAFETY_PH_MAX 8.5f
#define SAFETY_PH_CRITICAL_LOW 4.0f
#define SAFETY_PH_CRITICAL_HIGH 9.0f
#define SAFETY_PH_RATE_MAX_PER_MIN 1.0f
#define SAFETY_PH_FROZEN_EPSILON 0.005f
#define SAFETY_PH_FROZEN_SAMPLES 20
#define SAFETY_PH_RESPONSE_TIMEOUT_MS 90000
#define SAFETY_PH_RESPONSE_MIN_DELTA 0.03f

#define SAFETY_TDS_MIN 50.0f
#define SAFETY_TDS_MAX 2500.0f
#define SAFETY_TDS_FROZEN_EPSILON 0.5f
#define SAFETY_TDS_FROZEN_SAMPLES 20
#define SAFETY_TDS_RESPONSE_TIMEOUT_MS 120000
#define SAFETY_TDS_RESPONSE_MIN_DELTA 5.0f

#endif
