name: ESP-IDF Build and Release

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    container: espressif/idf:v5.1
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Build
        run: |
          . $IDF_PATH/export.sh
          idf.py build
          cd build
          esptool.py --chip esp32 merge_bin -o full_firmware.bin @flash_args

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: esp32-bins
          path: |
            build/full_firmware.bin
            build/partition_table/partition-table.bin
            build/bootloader/bootloader.bin

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: esp32-bins
          path: ./release_assets  # Force them into a specific folder

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          # Use the path to the folder we just created
          files: |
            release_assets/full_firmware.bin
            release_assets/partition-table.bin
            release_assets/bootloader.bin
          body: "Automated firmware build for ${{ github.ref_name }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}